---
sidebar: sidebar 
permalink: reference/dr-reference-roles.html 
keywords: how bluexp disaster recovery works, what is disaster recovery, bluexp, vmware, vcenter, draas, replicate, failover, failback, fail over, fail back, vmware cloud, netapp intelligent services 
summary: Die BlueXP disaster recovery verwendet Rollen, um den Zugriff jedes Benutzers auf bestimmte Funktionen und Aktionen zu regeln. 
---
= Rollenbasierter Zugriff auf Funktionen der BlueXP disaster recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die BlueXP disaster recovery verwendet Rollen, um den Zugriff jedes Benutzers auf bestimmte Funktionen und Aktionen zu regeln.

Der Dienst verwendet die folgenden Rollen, die spezifisch für die BlueXP disaster recovery sind.

* *Notfallwiederherstellungsadministrator*: Führen Sie beliebige Aktionen in der BlueXP disaster recovery durch.
* *Disaster Recovery-Failover-Administrator*: Führen Sie Failover- und Migrationsaktionen in der BlueXP disaster recovery durch.
* *Administrator der Notfallwiederherstellungsanwendung*: Erstellen und ändern Sie Replikationspläne und starten Sie Test-Failover.
* *Disaster Recovery Viewer*: Informationen in BlueXP disaster recovery anzeigen, aber keine Aktionen ausführen.


Diese Rollen sind spezifisch für die BlueXP disaster recovery und sind nicht dieselben wie die Plattformrollen, die in BlueXP verwendet werden. Weitere Informationen zu allen Rollen der BlueXP -Plattform finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Die BlueXP -Installations- und Administrationsdokumentation"^].

In der folgenden Tabelle sind die Aktionen aufgeführt, die jede BlueXP disaster recovery ausführen kann.

[cols="30,20a,20a,20a,20a"]
|===
| Funktion und Aktion | Notfallwiederherstellungsadministrator | Administrator für Notfallwiederherstellungs-Failover | Administrator der Notfallwiederherstellungsanwendung | Disaster Recovery-Viewer 


| Dashboard und alle Registerkarten anzeigen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Kostenlos testen  a| 
Ja.
 a| 
Nein
 a| 
Nein
 a| 
Nein



| Beginnen Sie mit der Erkennung von Workloads  a| 
Ja.
 a| 
Nein
 a| 
Nein
 a| 
Nein



| Lizenzinformationen anzeigen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Lizenz aktivieren  a| 
Ja.
 a| 
Nein
 a| 
Ja.
 a| 
Nein



5+| *Auf der Registerkarte „Sites“*: 


| Websites anzeigen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Websites hinzufügen, ändern oder löschen  a| 
Ja.
 a| 
Nein
 a| 
Nein
 a| 
Nein



5+| *Auf der Registerkarte Replikationspläne*: 


| Anzeigen von Replikationsplänen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Anzeigen von Replikationsplandetails  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Erstellen oder Ändern von Replikationsplänen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Nein



| Erstellen von Berichten  a| 
Ja.
 a| 
Nein
 a| 
Nein
 a| 
Nein



| Snapshots anzeigen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Durchführen von Failover-Tests  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Nein



| Durchführen von Failovern  a| 
Ja.
 a| 
Ja.
 a| 
Nein
 a| 
Nein



| Durchführen von Failbacks  a| 
Ja.
 a| 
Ja.
 a| 
Nein
 a| 
Nein



| Migrationen durchführen  a| 
Ja.
 a| 
Ja.
 a| 
Nein
 a| 
Nein



5+| *Auf der Registerkarte „Ressourcengruppen“*: 


| Anzeigen von Ressourcengruppen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Erstellen, Ändern oder Löschen von Ressourcengruppen  a| 
Ja.
 a| 
Nein
 a| 
Ja.
 a| 
Nein



5+| *Auf der Registerkarte „Jobüberwachung“*: 


| Jobs anzeigen  a| 
Ja.
 a| 
Nein
 a| 
Ja.
 a| 
Ja.



| Aufträge abbrechen  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Nein

|===