---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Einführung in BlueXP Disaster Recovery mit Amazon EVS und Amazon FSx für NetApp ONTAP. BlueXP Disaster Recovery ist ein lizenziertes Produktangebot, das vor der Nutzung erworben werden muss. Es gibt verschiedene Lizenztypen und verschiedene Möglichkeiten, Lizenzen zu erwerben. 
---
= Fügen Sie Ihrem BlueXP-Konto für Amazon EVS den BlueXP-Notfallwiederherstellungsdienst hinzu
:allow-uri-read: 


[role="lead"]
BlueXP Disaster Recovery ist ein lizenziertes Produktangebot, das vor der Nutzung erworben werden muss. Es gibt verschiedene Lizenztypen und verschiedene Möglichkeiten, Lizenzen zu erwerben. Eine Lizenz berechtigt Sie zum Schutz einer bestimmten Datenmenge für einen bestimmten Zeitraum.

Weitere Informationen zu BlueXP Disaster Recovery-Lizenzen finden Sie unter link:../get-started/dr-licensing.html["Lizenzierung für die Disaster Recovery von BlueXP einrichten"] .



== Lizenztypen

Es gibt zwei primäre Lizenztypen:

* NetApp bietet eine link:../get-started/dr-licensing.html["30-Tage-Testlizenz"] Damit können Sie BlueXP Disaster Recovery mit Ihren ONTAP- und VMware-Ressourcen evaluieren. Diese Lizenz ermöglicht eine 30-tägige Nutzung einer unbegrenzten Menge geschützter Kapazität.
* Erwerben Sie eine Produktionslizenz, wenn Sie DR-Schutz über die 30-tägige Testphase hinaus wünschen. Diese Lizenz ist über die Marktplätze aller NetApp Cloud-Partner erhältlich. Für diesen Leitfaden empfehlen wir jedoch den Erwerb Ihrer *NetApp Intelligent Services*-Lizenz für BlueXP Disaster Recovery über den Amazon AWS Marketplace. Weitere Informationen zum Erwerb einer Lizenz über den Amazon Marketplace finden Sie unter link:../get-started/dr-licensing.html["Abonnieren Sie ihn über AWS Marketplace"] .




== Bemessen Sie Ihren Kapazitätsbedarf für die Notfallwiederherstellung

Bevor Sie Ihre Lizenz erwerben, sollten Sie wissen, wie viel ONTAP-Speicherkapazität Sie schützen müssen. Einer der Vorteile von NetApp ONTAP Storage ist die hohe Effizienz, mit der NetApp Ihre Daten speichert. Alle in einem ONTAP-Volume gespeicherten Daten – wie z. B. VMware-Datenspeicher mit VMs – werden hocheffizient gespeichert. ONTAP nutzt standardmäßig drei Arten der Speichereffizienz beim Schreiben von Daten in physische Speicher: Komprimierung, Deduplizierung und Kompression. Das Ergebnis sind Speichereffizienzen zwischen 1,5:1 und 4:1, abhängig von den gespeicherten Datentypen. NetApp bietet eine  https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["Speichereffizienzgarantie"^] für bestimmte Arbeitslasten.

Dies ist ein Vorteil für Sie, da BlueXP Disaster Recovery die Kapazität für die Lizenzierung berechnet, nachdem alle ONTAP-Speichereffizienzen berücksichtigt wurden. Nehmen wir beispielsweise an, Sie haben einen 100 Terabyte (TiB) großen NFS-Datenspeicher in vCenter bereitgestellt, um 100 VMs zu hosten, die Sie mit dem Service schützen möchten. Nehmen wir außerdem an, dass beim Schreiben der Daten auf das ONTAP-Volume automatisch angewandte Speichereffizienztechniken dazu führen, dass diese VMs nur 33 TiB belegen (Speichereffizienz 3:1). BlueXP Disaster Recovery benötigt nur eine Lizenz für 33 TiB, nicht für 100 TiB. Dies kann die Gesamtbetriebskosten Ihrer DR-Lösung im Vergleich zu anderen DR-Lösungen deutlich senken.

.Schritte
. Um zu ermitteln, wie viele Daten auf jedem Volume verbraucht werden, auf dem sich ein zu schützender VMware-Datenspeicher befindet, ermitteln Sie den Kapazitätsverbrauch auf der Festplatte, indem Sie für jedes Volume den ONTAP-CLI-Befehl ausführen:  `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` .
+
Beispiel:

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. Notieren Sie den Wert *Total Physical Used* für jedes Volume. Dies ist die Datenmenge, die BlueXP Disaster Recovery schützen muss. Anhand dieses Werts bestimmen Sie, wie viel Kapazität Sie lizenzieren müssen.

