---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Nachdem der BlueXP Connector installiert wurde, müssen Sie alle ONTAP-Speicher- und VMware vCenter-Ressourcen integrieren, die am DR-Prozess teilnehmen. 
---
= Übersicht: BlueXP-Notfallwiederherstellung für Amazon EVS konfigurieren
:allow-uri-read: 


[role="lead"]
Nachdem Sie den BlueXP Connector installiert haben, müssen Sie alle ONTAP-Speicher- und VMware vCenter-Ressourcen, die am Disaster Recovery-Prozess teilnehmen, mit der BlueXP-Disaster Recovery integrieren.

* link:evs-deploy-guide-config-prereqs.html["Voraussetzungen für Amazon EVS mit BlueXP Disaster Recovery"]
* link:evs-deploy-guide-config-add-arrays.html["Fügen Sie ONTAP-Speicher-Arrays zur BlueXP-Notfallwiederherstellung hinzu"]
* link:evs-deploy-guide-enable-draas.html["Aktivieren Sie die BlueXP-Notfallwiederherstellung für Amazon EVS"]
* link:evs-deploy-guide-config-add-sites.html["Fügen Sie vCenter-Sites zur BlueXP-Notfallwiederherstellung hinzu"]
* link:evs-deploy-guide-config-add-vcenters.html["Fügen Sie vCenter-Cluster zur BlueXP-Notfallwiederherstellung hinzu"]

