---
sidebar: sidebar 
permalink: use/reports.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp, protection, reports 
summary: Durch die Überprüfung von Disaster Recovery-Berichten können Sie die Bereitschaft Ihrer Disaster Recovery analysieren. Vordefinierte Berichte enthalten eine Zusammenfassung von Failover und Failbacks, Replikationsdetails zu allen Standorten und Jobdetails für das vergangene Jahr. 
---
= Erstellen von Disaster-Recovery-Berichten
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Durch die Überprüfung von Disaster Recovery-Berichten können Sie die Bereitschaft Ihrer Disaster Recovery analysieren. Vordefinierte Berichte enthalten eine Zusammenfassung der Failover-Tests, Details zum Replizierungsplan und Jobdetails für alle Standorte innerhalb eines Kontos der letzten sieben Tage.

Sie können Berichte im HTML- oder JSON-Format herunterladen.


TIP: Sie können die HTML-Seite mit den Optionen Ihres Browsers in eine PDF-Datei konvertieren.

Der Download-Link ist sechs Stunden gültig.

.Schritte
. Wählen Sie in der linken Navigationsleiste von BlueXP  *Schutz* > *Disaster Recovery* > *Replikationspläne* aus.
. Wählen Sie oben auf der Seite *Bericht erstellen* aus.
. Wählen Sie das Dateiformat und den Zeitraum innerhalb der letzten 7 Tage aus.
. Wählen Sie *Erstellen*.
+

NOTE: Die Anzeige des Berichts kann einige Minuten dauern.

. Um einen Bericht herunterzuladen, wählen Sie *Download Report* aus und wählen ihn im Download-Ordner des Administrators aus.

