---
sidebar: sidebar 
permalink: get-started/dr-faq.html 
keywords: disaster recovery faq, disaster recovery frequently asked questions 
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= Häufig gestellte Fragen zur Disaster Recovery von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.

*Wie sieht die Disaster-Recovery-URL von BlueXP aus?*
Geben Sie für die URL in einem Browser Folgendes ein: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] Um auf die BlueXP Konsole zuzugreifen.

*Benötigen Sie eine Lizenz für die Nutzung von BlueXP Disaster Recovery?*
Für vollständigen Zugriff ist eine Disaster-Recovery-Lizenz von BlueXP erforderlich. Sie können es jedoch mit der kostenlosen Testversion ausprobieren.

Weitere Informationen zur Einrichtung einer Lizenzierung für die Disaster Recovery von BlueXP finden Sie unter link:../get-started/dr-licensing.html["Disaster-Recovery-Lizenzen für BlueXP einrichten"].

*Wie greifen Sie auf BlueXP Disaster Recovery zu?*
Für die Disaster Recovery von BlueXP ist keine Aktivierung erforderlich. Die Disaster-Recovery-Option wird automatisch in der linken Navigation von BlueXP angezeigt.
