---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites 
summary: 'Erste Schritte mit BlueXP Disaster Recovery: Verifizieren Sie Unterstützung für Ihre Umgebung, Ihren Netzwerkzugriff, Ihre Anmeldung und Ihren Webbrowser.' 
---
= Voraussetzungen für die Disaster Recovery von BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Prüfen Sie zunächst die Betriebsumgebung, die Anmeldung, den Netzwerkzugriff und den Webbrowser.

Um die Disaster Recovery von BlueXP zu nutzen, sollten Sie sicherstellen, dass Ihre Umgebung die folgenden Anforderungen erfüllt:

* Lokale VMware Arbeitsumgebung mit NetApp Storage
* Auf AWS:
+
** Ein Dateisystem von Amazon FSX für NetApp ONTAP. Informationen zur ONTAP finden Sie in der Dokumentation zu Amazon FSX auf https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["Erste Schritte"^].
** Ein VMware Konto mit einem softwaredefinierten Datacenter (SDDC) auf AWS, das auch als Virtual Machines Cloud bezeichnet wird. Verwenden Sie in der VMware Cloud Console die Dienstrollen Administrator und NSX Cloud Administrator. Verwenden Sie auch den Organisationseigentümer für die Rolle Organisation. Siehe https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Cloud-Dokumentation für Virtual Machines"^].
** Verknüpfen Sie das SDDC mit Amazon FSX for NetApp ONTAP. Siehe https://vmc.techzone.vmware.com/fsx-guide#overview["VMware Cloud on AWS lässt sich jetzt in Amazon FSX for NetApp ONTAP integrieren"^].


* In BlueXP:
+
** Die Arbeitsumgebung von BlueXP wurde mit Amazon FSX for ONTAP und AWS Zugangsdaten erweitert.
** Der BlueXP Connector muss in BlueXP eingerichtet werden. Der On-Premises- und Cloud Connector sollten sowohl mit dem On-Premises- als auch mit VMware Cloud (VMC) vCenter mit ESXis verbunden sein. Dadurch können die Backup-, Failover-, Failback- und Migrationsfunktionen ordnungsgemäß mit den erforderlichen Netzwerk- und Skriptfunktionen arbeiten.
+
Der BlueXP Connector erfordert Anmeldedaten für sowohl die Quell- als auch die Ziel-vCenter Server. Siehe https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["BlueXP Quick Start Guide"^] Und https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html["BlueXP Netzwerkinformationen"^].

** Um sicherzustellen, dass die Prozesse der Anwendungskonsistenz erfolgreich sind, stellen Sie sicher, dass die folgenden Voraussetzungen erfüllt sind:
+
*** Stellen Sie sicher, dass VMware-Tools (oder Open VM-Tools) auf den zu schützenden VMs ausgeführt werden.
*** Bei Windows VMs, auf denen SQL oder Oracle oder beides ausgeführt wird, sollten die Datenbanken ihre VSS-Writer aktivieren, und die Datenbanken sollten sich in einem stabilen Zustand befinden.
*** Bei Oracle-Datenbanken, die auf einem Linux-Betriebssystem ausgeführt werden, sollte die Benutzerauthentifizierung des Betriebssystems für die Rolle „Oracle Database SYSDBA“ aktiviert sein.





