---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Um das Disaster Recovery von BlueXP zu nutzen, führen Sie ein paar Schritte aus, um es einzurichten. 
---
= Richten Sie Ihre Infrastruktur für die Disaster Recovery von BlueXP ein
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Um das Disaster Recovery von BlueXP zu nutzen, müssen Sie es in wenigen Schritten sowohl in Amazon Web Services (AWS) als auch in BlueXP einrichten.


TIP: Prüfen link:../get-started/dr-prerequisites.html["Voraussetzungen"] Und stellen Sie sicher, dass Ihre Umgebung bereit ist.



== Machen Sie sich bereit für das Disaster Recovery von BlueXP

* Verifizieren Ihrer Produktionsumgebung:
+
** Stellen Sie sicher, dass VMs, die Sie sichern möchten, auf NFS-Datastores (mit ONTAP NFS-Volumes) oder VMFS-Datastores (mit NetApp iSCSI LUNs) gehostet werden.
** Stellen Sie sicher, dass Sie über Zugangsdaten und Zugriffsschlüssel für Ihre lokalen ONTAP Arrays, vCenter und auf AWS gehosteten VMware Cloud-Instanzen verfügen.


* Disaster-Recovery-Standort erstellen oder überprüfen
+
** Erstellen oder überprüfen Sie, ob Ihr Amazon FSX Dateisystem bereit ist.
** Stellen Sie sicher, dass die Quell- und Ziel-VMs Peering sind.






== Richten Sie VMware Cloud for AWS SDDC ein

Softwaredefiniertes Datacenter (SDDC) von VMware Cloud für AWS einrichten

* Erstellen Sie ein Dateisystem von Amazon FSX für ONTAP. Bereitstellung und Konfiguration von FSX für ONTAP Amazon FSX für NetApp ONTAP ist ein vollständig gemanagter Service, der zuverlässigen, skalierbaren, hochperformanten und funktionsreichen File Storage auf dem beliebten NetApp ONTAP Filesystem bietet.
* Befolgen Sie die Schritte hier https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["Verlinken"^] und hier https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Schnellstart für Amazon FSX for NetApp ONTAP"] , um FSX für NetApp ONTAP bereitzustellen und zu konfigurieren.
* Fügen Sie Amazon FSX for NetApp ONTAP in die Arbeitsumgebung ein und fügen Sie AWS-Zugangsdaten für FSX for ONTAP hinzu.
* In AWS müssen Sie folgende Schritte durchführen:
+
** VMware Cloud on AWS implementieren und konfigurieren
** Verwenden Sie ein VMware Konto und stellen Sie das SDDC bereit. Stellen Sie sicher, dass das SDDC über Konnektivität mit FSX for ONTAP verfügt.






=== Implementieren Sie VMware Cloud

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud auf AWS"^] Cloud-native Arbeitsumgebung für VMware-basierte Workloads im AWS Ecosystem Jedes VMware SDDC (softwaredefiniertes Datacenter) wird in einer Amazon Virtual Private Cloud (VPC) ausgeführt und bietet ein vollständiges VMware Stack (einschließlich vCenter Server), NSX-T Software-definiertes Networking, vSAN Software-definierten Storage und einen oder mehrere ESXi Hosts, die Computing- und Storage-Ressourcen für die Workloads zur Verfügung stellen.

Gehen Sie folgendermaßen vor, um eine VMC-Umgebung auf AWS zu konfigurieren https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["Verlinken"^]. Ein Pilot-Light-Cluster kann auch für Disaster Recovery-Zwecke verwendet werden.



== Lizenzierung einrichten

Mit BlueXP Disaster Recovery können Sie sich für eine kostenlose 90-Tage-Testversion anmelden.

Sie können eine der folgenden Optionen erwerben:

* Ein PAYGO-Abonnement (Pay-as-you-go) mit AWS Marketplace
* Bring-Your-Own-License (BYOL) bei einer NetApp-Lizenzdatei (NLF)


Siehe link:../get-started/dr-licensing.html["Disaster-Recovery-Lizenzen für BlueXP einrichten"].
