---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Um das Disaster Recovery von BlueXP zu nutzen, führen Sie ein paar Schritte aus, um es einzurichten. 
---
= Richten Sie Ihre Infrastruktur für die Disaster Recovery von BlueXP ein
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Um das Disaster Recovery von BlueXP zu nutzen, müssen Sie es in wenigen Schritten sowohl in Amazon Web Services (AWS) als auch in BlueXP einrichten.


TIP: Prüfen link:../get-started/dr-prerequisites.html["Voraussetzungen"] Und stellen Sie sicher, dass Ihre Umgebung bereit ist.



== Machen Sie sich bereit für die BlueXP  Disaster Recovery zur Sicherung vor Ort

Vergewissern Sie sich, dass die folgenden Anforderungen erfüllt sind, bevor Sie BlueXP  Disaster Recovery für On-Premises-zu-On-Premises-Sicherung einrichten:

* ONTAP-Lagerung
+
** Stellen Sie sicher, dass Sie über ONTAP-Anmeldeinformationen verfügen.
** Disaster-Recovery-Standort erstellen oder überprüfen
** Ziel-ONTAP SVM erstellen oder überprüfen.
** Stellen Sie sicher, dass die ONTAP SVMs Ihrer Quell- und Ziel-SVMs geeignet sind.


* VCenter-Cluster
+
** Stellen Sie sicher, dass die VMs, die Sie sichern möchten, auf NFS-Datenspeichern (mit ONTAP NFS Volumes) oder VMFS-Datenspeichern (mit NetApp iSCSI LUNs) gehostet werden.
** Prüfung link:../reference/vcenter-privileges.html["VCenter Privileges"]für BlueXP  DR erforderlich.
** Erstellen Sie ein Disaster Recovery-Benutzerkonto (nicht das standardmäßige vCenter-Administratorkonto) und weisen Sie dem Konto die vCenter Privileges zu.






== Machen Sie sich bereit für die BlueXP  Disaster Recovery für den Schutz vor Ort in der Cloud mit AWS

Um BlueXP  Disaster Recovery für den On-Premises- zu-Cloud-Schutz mit AWS einzurichten, müssen Sie Folgendes einrichten:

* AWS FSX für NetApp ONTAP einrichten
* Richten Sie VMware Cloud on AWS SDDC ein




=== AWS FSX für NetApp ONTAP einrichten

* Erstellen Sie ein Dateisystem von Amazon FSX für NetApp ONTAP.
+
** Bereitstellung und Konfiguration von FSX für ONTAP Amazon FSX for NetApp ONTAP ist ein vollständig gemanagter Service, der auf dem NetApp ONTAP Filesystem als Basis äußerst zuverlässigen, skalierbaren, hochperformanten und funktionsreichen File-Storage bietet.
** Befolgen Sie die Schritte in https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["Technischer Bericht 4938: Amazon FSX ONTAP als NFS-Datastore mit VMware Cloud on AWS mounten"^] und https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Schnellstart für Amazon FSX for NetApp ONTAP"], um FSX für ONTAP bereitzustellen und zu konfigurieren.


* Fügen Sie Amazon FSX for ONTAP in die Arbeitsumgebung ein und fügen Sie AWS-Zugangsdaten für FSX for ONTAP hinzu.
* ONTAP-ZielSVM in AWS FSX for ONTAP-Instanz erstellen oder überprüfen.
* Konfigurieren Sie die Replizierung zwischen Ihrem lokalen Quell-ONTAP-Cluster und Ihrer FSX for ONTAP-Instanz in BlueXP .


Detaillierte Schritte finden Sie unter https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["So richten Sie ein FSX für ONTAP-Arbeitsumgebung ein"^].



=== Richten Sie VMware Cloud on AWS SDDC ein

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud auf AWS"^] Cloud-native Arbeitsumgebung für VMware-basierte Workloads im AWS Ecosystem Jedes VMware SDDC (softwaredefiniertes Datacenter) wird in einer Amazon Virtual Private Cloud (VPC) ausgeführt und bietet ein vollständiges VMware Stack (einschließlich vCenter Server), NSX-T Software-definiertes Networking, vSAN Software-definierten Storage und einen oder mehrere ESXi Hosts, die Computing- und Storage-Ressourcen für die Workloads zur Verfügung stellen.

Um eine VMware Cloud-Umgebung auf AWS zu konfigurieren, folgen Sie den Schritten in https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["Implementieren und Konfigurieren der Virtualisierungsumgebung auf AWS"^]. Ein Pilot-Light-Cluster kann auch für Disaster-Recovery-Zwecke verwendet werden.
