---
sidebar: sidebar 
permalink: release-notes/dr-whats-new.html 
keywords: disaster recovery, bluexp, disaster recovery, vmware, vcenter, draas, disaster 
summary: BlueXP Disaster Recovery ist ein Cloud-basierter Disaster Recovery Service, der Disaster Recovery Workflows automatisiert. Mit der Disaster Recovery für VMware von BlueXP können Sie Ihre lokalen VMware-Workloads, auf denen ONTAP Storage ausgeführt wird, auf ein softwaredefiniertes VMware Datacenter in Public Clouds als Disaster-Recovery-Standort mithilfe von NetApp Cloud-Storage replizieren. 
---
= Neuerungen bei der BlueXP  Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Neuerungen bei BlueXP Disaster Recovery.



== 30 Juni 2025

Version 4.2.4P2



=== Verbesserungen bei der Erkennung

Dieses Update verbessert den Erkennungsprozess und verkürzt so die für die Erkennung benötigte Zeit.



== 23 Juni 2025

Version 4.2.4P1



=== Verbesserungen der Subnetzzuordnung

Dieses Update erweitert den Dialog „Subnetzzuordnung hinzufügen und bearbeiten“ um eine neue Suchfunktion. Sie können nun schnell bestimmte Subnetze durch die Eingabe von Suchbegriffen finden, was die Verwaltung von Subnetzzuordnungen vereinfacht.



== 9 Juni 2025

Version 4.2.4



=== Unterstützung für Windows Local Administrator Password Solution (LAPS)

Windows Local Administrator Password Solution (Windows LAPS) ist eine Windows-Funktion, die das Kennwort eines lokalen Administratorkontos im Active Directory automatisch verwaltet und sichert.

Sie können nun Subnetzzuordnungsoptionen auswählen und die LAPS-Option aktivieren, indem Sie die Domänencontrollerdetails angeben. Mit dieser Option müssen Sie nicht für jede Ihrer virtuellen Maschinen ein Kennwort angeben.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



== 13 Mai 2025

Version 4.2.3



=== Subnetzzuordnung

Mit diesem Release können Sie IP-Adressen bei einem Failover auf neue Weise mithilfe der Subnetzzuordnung managen, wodurch Sie Subnetze für jedes vCenter hinzufügen können. Dabei definieren Sie den IPv4 CIDR, das Standard-Gateway und den DNS für jedes virtuelle Netzwerk.

Bei einem Failover ermittelt die Disaster Recovery von BlueXP  die geeignete IP-Adresse jeder vNIC, indem das für das zugeordnete virtuelle Netzwerk bereitgestellte CIDR betrachtet und es zum Ableiten der neuen IP-Adresse verwendet wird.

Beispiel:

* NetworkA = 10.1.1.0/24
* NetzwerkB = 192.168.1.0/24


VM1 verfügt über eine vNIC (10.1.1.50), die mit NetworkA verbunden ist. NetworkA wird in den Einstellungen des Replikationsplans zu NetworkB zugeordnet.

Bei einem Failover ersetzt die Disaster Recovery von BlueXP  den Teil Netzwerk der ursprünglichen IP-Adresse (10.1.1) und behält die Host-Adresse (.50) der ursprünglichen IP-Adresse (10.1.1.50) bei. Für VM1 betrachtet die BlueXP  Disaster Recovery die CIDR-Einstellungen für NetworkB und verwendet den Netzwerk-B-Teil 192.168.1, während der Host-Teil (.50) beibehalten wird, um die neue IP-Adresse für VM1 zu erstellen. Die neue IP wird 192.168.1.50.

Zusammenfassend bleibt die Host-Adresse unverändert, während die Netzwerkadresse durch das ersetzt wird, was in der Subnetz-Zuordnung des Standorts konfiguriert ist. So lässt sich die IP-Adressenzuweisung beim Failover einfacher managen, insbesondere wenn Sie hunderte Netzwerke und tausende VMs managen müssen.

Weitere Informationen zum Einbeziehen der Subnetzzuordnung in Ihre Standorte finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Fügen Sie vCenter-Serverstandorte hinzu"].



=== Schutz überspringen

Sie können jetzt den Schutz überspringen, damit der Dienst nach einem Failover des Replikationsplans nicht automatisch eine umgekehrte Schutzbeziehung erstellt. Dies ist nützlich, wenn Sie auf dem wiederhergestellten Standort weitere Vorgänge durchführen möchten, bevor Sie ihn in BlueXP  Disaster Recovery wieder online schalten.

Wenn Sie ein Failover initiieren, erstellt der Service standardmäßig automatisch eine umgekehrte Schutzbeziehung für jedes Volume im Replizierungsplan, wenn der ursprüngliche Quellstandort online ist. Das bedeutet, dass der Service eine SnapMirror-Beziehung vom Zielstandort zurück zum Quellstandort erstellt. Der Service kehrt auch automatisch die SnapMirror-Beziehung um, wenn Sie ein Failback initiieren.

Wenn Sie ein Failover starten, können Sie jetzt eine Option *Skip Protection* wählen. Damit wird die SnapMirror-Beziehung nicht automatisch rückgängig gemacht. Stattdessen verlässt es das beschreibbare Volume auf beiden Seiten des Replizierungsplans.

Nachdem der ursprüngliche Quellstandort wieder online ist, können Sie den umgekehrten Schutz einrichten, indem Sie im Menü Aktionen des Replikationsplans die Option *Ressourcen schützen* auswählen. Dadurch wird versucht, für jedes Volume im Plan eine umgekehrte Replikationsbeziehung zu erstellen. Sie können diesen Job wiederholt ausführen, bis der Schutz wiederhergestellt ist. Wenn der Schutz wiederhergestellt ist, können Sie ein Failback auf die übliche Weise initiieren.

Weitere Informationen zum Übersprungsschutz finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover von Anwendungen an einen Remote-Standort"].



=== SnapMirror plant Updates im Replizierungsplan

BlueXP  Disaster Recovery unterstützt nun die Verwendung externer Snapshot-Managementlösungen, wie z. B. der native Richtlinienplaner von ONTAP SnapMirror oder die Integration von Produkten anderer Anbieter mit ONTAP. Wenn jeder Datastore (Volume) im Replizierungsplan bereits über eine SnapMirror-Beziehung verfügt, die an anderer Stelle gemanagt wird, können Sie diese Snapshots als Wiederherstellungspunkte in der BlueXP  Disaster Recovery verwenden.

Aktivieren Sie zum Konfigurieren im Abschnitt Replizierungsplan > Ressourcenzuordnung das Kontrollkästchen *Plattform-verwaltete Backups und Aufbewahrungszeitpläne verwenden*, wenn Sie die Datenspeicherzuordnung konfigurieren.

Wenn die Option ausgewählt ist, wird in BlueXP  Disaster Recovery kein Backup-Zeitplan konfiguriert. Sie müssen jedoch weiterhin einen Aufbewahrungszeitplan konfigurieren, da darüber hinaus Snapshots für Test-, Failover- und Failback-Vorgänge erstellt werden können.

Nach der Konfiguration erstellt der Service keine regelmäßig geplanten Snapshots, sondern verlässt sich darauf, dass die externe Einheit diese Snapshots erstellt und aktualisiert.

Weitere Informationen zur Verwendung externer Snapshot-Lösungen im Replikationsplan finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



== Bis 16. April 2025

Version 4.2.2



=== Geplante Ermittlung für VMs

Bei der Disaster Recovery von BlueXP  werden alle 24 Stunden einmal erkannt. Mit dieser Version können Sie den Zeitplan zur Bestandsaufnahme nun an Ihre Anforderungen anpassen und die Performance bei Bedarf verringern. Wenn Sie beispielsweise über eine große Anzahl von VMs verfügen, können Sie den Erkennungszeitplan so einstellen, dass er alle 48 Stunden ausgeführt wird. Wenn Sie über eine geringe Anzahl von VMs verfügen, können Sie den Erkennungszeitplan so einstellen, dass er alle 12 Stunden ausgeführt wird.

Wenn Sie die Ermittlung nicht per wan planen, können Sie die Option für die geplante Ermittlung deaktivieren und die Ermittlung jederzeit manuell aktualisieren.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Fügen Sie vCenter-Serverstandorte hinzu"].



=== Unterstützung für Ressourcengruppen-Datastore

Zuvor können Sie Ressourcengruppen nur nach VMs erstellen. Mit diesem Release können Sie eine Ressourcengruppe nach Datastores erstellen. Wenn Sie einen Replikationsplan erstellen und eine Ressourcengruppe für diesen Plan erstellen, werden alle VMs in einem Datenspeicher aufgelistet. Dies ist nützlich, wenn Sie über eine große Anzahl von VMs verfügen und sie nach Datenspeicher gruppieren möchten.

Sie haben folgende Möglichkeiten, eine Ressourcengruppe mit einem Datastore zu erstellen:

* Wenn Sie eine Ressourcengruppe mithilfe von Datastores hinzufügen, wird eine Liste der Datastores angezeigt. Sie können einen oder mehrere Datastores auswählen, um eine Ressourcengruppe zu erstellen.
* Wenn Sie einen Replizierungsplan erstellen und eine Ressourcengruppe innerhalb des Plans erstellen, werden die VMs in den Datenspeichern angezeigt.


Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Benachrichtigungen über Ablauf der kostenlosen Testversion oder Lizenz

Diese Version enthält Benachrichtigungen, dass die kostenlose Testversion in 60 Tagen abläuft, um sicherzustellen, dass Sie Zeit haben, um eine Lizenz zu erhalten. Diese Version enthält auch Benachrichtigungen an dem Tag, an dem die Lizenz abläuft.



=== Benachrichtigung über Service-Updates

Mit diesem Release wird oben ein Banner angezeigt, das anzeigt, dass Services aktualisiert werden und der Service in den Wartungsmodus versetzt wird. Das Banner wird angezeigt, wenn der Dienst aktualisiert wird, und wird nach Abschluss der Aktualisierung nicht mehr angezeigt. Sie können zwar weiterhin in der Benutzeroberfläche arbeiten, während das Upgrade ausgeführt wird, Sie können jedoch keine neuen Jobs senden. Geplante Jobs werden ausgeführt, nachdem die Aktualisierung abgeschlossen ist und der Dienst in den Produktionsmodus zurückkehrt.



== 10 März 2025

Version 4.2.1



=== Intelligente Proxy-Unterstützung

Der BlueXP -Connector unterstützt den intelligenten Proxy. Ein intelligenter Proxy ist eine einfache, sichere und effiziente Möglichkeit, Ihre On-Premises-Umgebung mit dem BlueXP -Service zu verbinden. Sie stellt eine sichere Verbindung zwischen Ihrer Umgebung und dem BlueXP -Dienst her, ohne dass ein VPN oder ein direkter Internetzugang erforderlich ist. Diese optimierte Proxy-Implementierung entlastet den API-Verkehr innerhalb des lokalen Netzwerks.

Wenn ein Proxy konfiguriert ist, versucht BlueXP  Disaster Recovery, direkt mit VMware oder ONTAP zu kommunizieren und verwendet den konfigurierten Proxy, wenn die direkte Kommunikation fehlschlägt.

Für die Implementierung eines BlueXP  Disaster Recovery Proxy ist eine Port 443-Kommunikation zwischen dem Connector und allen vCenter-Servern und ONTAP-Arrays über ein HTTPS-Protokoll erforderlich. Der BlueXP  Disaster Recovery-Agent im Connector kommuniziert direkt mit VMware vSphere, VC oder ONTAP, wenn Aktionen durchgeführt werden.

Weitere Informationen zum intelligenten Proxy für die Disaster Recovery von BlueXP  finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html["Richten Sie Ihre Infrastruktur für die Disaster Recovery von BlueXP ein"].

Weitere Informationen über die Einrichtung eines allgemeinen Proxys in BlueXP  finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Konfigurieren Sie einen Konnektor für die Verwendung eines Proxy-Servers"^].



=== Beenden Sie die kostenlose Testversion jederzeit

Sie können die kostenlose Testversion an jedem Zinken stoppen oder Sie können warten, bis sie abläuft.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html#end-the-free-trial["Beenden Sie die kostenlose Testversion"].



== 19 Februar 2025

Version 4.2



=== Unterstützung von ASA r2 für VMs und Datastores auf VMFS Storage

Diese Version von BlueXP  Disaster Recovery unterstützt ASA r2 für VMs und Datastores auf VMFS-Storage. Auf einem ASA r2 System unterstützt die ONTAP Software grundlegende SAN-Funktionen und beseitigt gleichzeitig Funktionen, die in SAN-Umgebungen nicht unterstützt werden.

Dieser Release unterstützt die folgenden Funktionen für ASA r2:

* Provisioning von Konsistenzgruppen für primären Storage (nur flache Konsistenzgruppe, d. h. nur eine Ebene ohne hierarchische Struktur)
* Backup-Vorgänge (Konsistenzgruppen), einschließlich SnapMirror-Automatisierung


Die Unterstützung für ASA r2 für BlueXP  Disaster Recovery verwendet ONTAP 9.16.1.

Während Datastores auf einem ONTAP Volume oder einer ASA r2 Storage-Einheit gemountet werden können, kann eine Ressourcengruppe in der Disaster Recovery mit BlueXP  nicht sowohl einen Datenspeicher aus ONTAP als auch einen Datenspeicher aus ASA r2 umfassen. Sie können entweder einen Datenspeicher aus ONTAP oder einen Datenspeicher aus ASA r2 in einer Ressourcengruppe auswählen.



== 30 Oktober 2024



=== Berichterstellung

Sie können jetzt Berichte erstellen und herunterladen, um Ihre Umgebung zu analysieren. Vordefinierte Berichte fassen Failover und Failbacks zusammen, zeigen Replikationsdetails auf allen Standorten an und zeigen Jobdetails der letzten sieben Tage an.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/reports.html["Erstellen von Disaster-Recovery-Berichten"].



=== 30 Tage kostenlos testen

Sie können sich jetzt für eine kostenlose 30-Tage-Testversion von BlueXP  Disaster Recovery anmelden. Zuvor waren kostenlose Testversionen für 90 Tage.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Lizenzierung einrichten"].



=== Deaktivieren und aktivieren Sie Replikationspläne

Eine frühere Version beinhaltete Aktualisierungen der Planungsstruktur für Failover-Tests, die zur Unterstützung von täglichen und wöchentlichen Zeitplänen erforderlich war. Für dieses Update mussten Sie alle vorhandenen Replikationspläne deaktivieren und wieder aktivieren, damit Sie die neuen täglichen und wöchentlichen Failover-Testpläne verwenden können. Dies ist eine einmalige Anforderung.

Und so funktioniert es:

. Wählen Sie im oberen Menü *Replikationspläne* aus.
. Wählen Sie einen Plan aus, und klicken Sie auf das Symbol Aktionen, um das Dropdown-Menü anzuzeigen.
. Wählen Sie *Deaktivieren*.
. Wählen Sie nach ein paar Minuten *enable*.




=== Ordnerzuordnung

Wenn Sie einen Replizierungsplan erstellen und Rechenressourcen zuordnen, können Sie jetzt Ordner zuordnen, sodass VMs in einem Ordner wiederhergestellt werden, den Sie für Datacenter, Cluster und Host angeben.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== VM-Details für Failover, Failback und Test-Failover verfügbar

Wenn ein Fehler auftritt und Sie einen Failover starten, ein Failback durchführen oder den Failover testen, können Sie jetzt die Details der VMs sehen und ermitteln, welche VMs nicht neu gestartet wurden.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover von Anwendungen an einen Remote-Standort"].



=== VM-Boot-Verzögerung mit bestellter Boot-Sequenz

Wenn Sie einen Replizierungsplan erstellen, können Sie jetzt für jede VM im Plan eine Boot-Verzögerung festlegen. So können Sie eine Sequenz für die VMs festlegen, die gestartet werden soll, um sicherzustellen, dass alle Ihre Priorität 1 VMs ausgeführt werden, bevor nachfolgende VMs mit Priorität gestartet werden.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Informationen zum VM-Betriebssystem

Wenn Sie einen Replikationsplan erstellen, können Sie nun das Betriebssystem für jede VM im Plan sehen. Dies ist hilfreich bei der Entscheidung, wie VMs in einer Ressourcengruppe gruppiert werden sollen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Aliasing für VM-Namen

Wenn Sie einen Replikationsplan erstellen, können Sie den VM-Namen auf dem Disaster Recovery Sit nun ein Präfix und ein Suffix hinzufügen. Dadurch können Sie einen aussagekräftigeren Namen für die VMs im Plan verwenden.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Alte Snapshots bereinigen

Sie können alle Snapshots löschen, die nicht mehr über die angegebene Aufbewahrungszahl hinaus benötigt werden. Snapshots können sich im Laufe der Zeit ansammeln, wenn Sie die Anzahl der Snapshot-Aufbewahrung senken, und Sie können sie jetzt entfernen, um Speicherplatz freizugeben. Dies ist jederzeit nach Bedarf oder beim Löschen eines Replikationsplans möglich.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Verwalten von Standorten, Ressourcengruppen, Replikationsplänen, Datastores und Informationen zu virtuellen Maschinen"].



=== Snapshots abgleichen

Sie können jetzt Snapshots abgleichen, die nicht synchron zwischen Quelle und Ziel sind. Dies kann vorkommen, wenn Snapshots auf einem Ziel außerhalb der Disaster Recovery von BlueXP  gelöscht werden. Der Dienst löscht den Snapshot auf der Quelle automatisch alle 24 Stunden. Sie können dies jedoch nach Bedarf durchführen. Mit dieser Funktion können Sie sicherstellen, dass die Snapshots über alle Standorte hinweg konsistent sind.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Verwalten von Replikationsplänen"].



== 20 September 2024



=== Unterstützung von lokalen bis lokalen VMware VMFS-Datastores

Diese Version umfasst Unterstützung für VMs, die auf VMware vSphere VMFS-Datastores (Virtual Machine File System) für iSCSI und FC gemountet sind und in lokalem Storage geschützt sind. Zuvor bot der Service eine Technologievorschau, die VMFS-Datastores für iSCSI und FC unterstützte.

Folgende Punkte sollten in Bezug auf iSCSI- und FC-Protokolle zusätzlich beachtet werden:

* FC-Unterstützung ist für Front-End-Protokolle des Clients, nicht für Replizierung.
* Die Disaster Recovery von BlueXP  unterstützt nur eine einzige LUN pro ONTAP Volume. Das Volume sollte nicht über mehrere LUNs verfügen.
* Bei jedem Replizierungsplan sollte das Ziel-ONTAP-Volume die gleichen Protokolle verwenden wie das Quell-ONTAP-Volume, auf dem die geschützten VMs gehostet werden. Wenn z. B. die Quelle ein FC-Protokoll verwendet, sollte das Ziel auch FC verwenden.




== 2 August 2024



=== Unterstützung von lokalen bis lokalen VMware VMFS-Datastores für FC

Diese Version enthält eine Technologievorschau von Unterstützung für VMs, die auf VMware vSphere VMFS-Datastores (Virtual Machine File System) für FC-Schutz auf lokalem Storage gemountet sind. Zuvor wurde eine Technologievorschau bereitgestellt, die VMFS-Datastores für iSCSI unterstützt.


NOTE: NetApp berechnet Ihnen keine Kosten für vorab angezeigte Workload-Kapazität.



=== Job wird abgebrochen

Mit diesem Release können Sie nun einen Job in der Job Monitor-Benutzeroberfläche abbrechen.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Überwachen von Jobs"].



== 17 Juli 2024



=== Zeitpläne für Failover-Tests

Diese Version enthält Updates der Zeitplanstruktur für Failover-Tests, die zur Unterstützung der täglichen und wöchentlichen Zeitpläne benötigt wurde. Für dieses Update müssen Sie alle vorhandenen Replikationspläne deaktivieren und wieder aktivieren, damit Sie die neuen täglichen und wöchentlichen Failover-Testpläne verwenden können. Dies ist eine einmalige Anforderung.

Und so funktioniert es:

. Wählen Sie im oberen Menü *Replikationspläne* aus.
. Wählen Sie einen Plan aus, und klicken Sie auf das Symbol Aktionen, um das Dropdown-Menü anzuzeigen.
. Wählen Sie *Deaktivieren*.
. Wählen Sie nach ein paar Minuten *enable*.




=== Aktualisierungen des Replikationsplans

Diese Version enthält Aktualisierungen der Daten des Replikationsplans, wodurch das Problem „Snapshot nicht gefunden“ behoben wird. Dies erfordert, dass Sie die Aufbewahrungszahl in allen Replikationsplänen auf 1 ändern und einen On-Demand-Snapshot initiieren. Dieser Prozess erstellt ein neues Backup und entfernt alle älteren Backups.

Und so funktioniert es:

. Wählen Sie im oberen Menü *Replikationspläne* aus.
. Wählen Sie den Replikationsplan aus, klicken Sie auf die Registerkarte *Failover Mapping* und klicken Sie auf das Bleistiftsymbol *Bearbeiten*.
. Klicken Sie auf den Pfeil *Datastores*, um ihn zu erweitern.
. Notieren Sie sich den Wert der Aufbewahrungszahl im Replizierungsplan. Sie müssen diesen ursprünglichen Wert wieder aktivieren, wenn Sie mit diesen Schritten fertig sind.
. Verringern Sie die Anzahl auf 1.
. Initiieren Sie einen On-Demand-Snapshot. Wählen Sie dazu auf der Seite Replizierungsplan den Plan aus, klicken Sie auf das Aktionen-Symbol und wählen Sie *Snapshot jetzt erstellen* aus.
. Nachdem der Snapshot-Job erfolgreich abgeschlossen wurde, erhöhen Sie die Anzahl im Replikationsplan wieder auf den ursprünglichen Wert, den Sie im ersten Schritt angegeben haben.
. Wiederholen Sie diese Schritte für alle vorhandenen Replikationspläne.




== 5 Juli 2024

Diese BlueXP Disaster Recovery-Version umfasst die folgenden Updates:



=== Unterstützung der AFF A-Series

Dieser Release unterstützt die Hardware-Plattformen der NetApp AFF A-Series.



=== Unterstützung von lokalen bis lokalen VMware VMFS-Datastores

Diese Version enthält eine Technologievorschau von Unterstützung für VMs, die auf VMware vSphere VMFS-Datastores (Virtual Machine File System) gemountet sind und auf lokalem Storage geschützt sind. In dieser Version wird Disaster Recovery in einer Technologievorschau für lokale VMware-Workloads in lokale VMware-Umgebungen mit VMFS-Datastores unterstützt.


NOTE: NetApp berechnet Ihnen keine Kosten für vorab angezeigte Workload-Kapazität.



=== Aktualisierungen des Replikationsplans

Sie können einen Replizierungsplan einfacher hinzufügen, indem Sie VMs auf der Seite Anwendungen nach Datenspeicher filtern und auf der Seite Ressourcenzuordnung weitere Zieldetails auswählen. Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Bearbeiten Sie Replikationspläne

Mit dieser Version wurde die Seite Failover Mappings für eine bessere Übersichtlichkeit verbessert.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Pläne verwalten"].



=== Bearbeiten Sie VMs

Mit dieser Version beinhaltete der Prozess zum Bearbeiten von VMs im Plan einige kleinere Verbesserungen der Benutzeroberfläche.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Managen von VMs"].



=== Failover-Updates

Bevor Sie einen Failover initiieren, können Sie nun den Status der VMs ermitteln und bestimmen, ob sie ein- oder ausgeschaltet sind. Mit dem Failover-Prozess können Sie jetzt einen Snapshot erstellen oder die Snapshots auswählen.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover von Anwendungen an einen Remote-Standort"].



=== Zeitpläne für Failover-Tests

Sie können nun die Failover-Tests bearbeiten und tägliche, wöchentliche und monatliche Zeitpläne für den Failover-Test festlegen.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Pläne verwalten"].



=== Aktualisierung der erforderlichen Informationen

Informationen zu den BlueXP  Disaster Recovery-Voraussetzungen wurden aktualisiert.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-prerequisites.html["Voraussetzungen für die Disaster Recovery von BlueXP"].



== 15 Mai 2024

Diese BlueXP Disaster Recovery-Version umfasst die folgenden Updates:



=== Replizierung von VMware-Workloads vor Ort

Diese Funktion wird jetzt als allgemeine Verfügbarkeitsfunktion veröffentlicht. Zuvor war es eine Technologievorschau mit eingeschränkter Funktionalität.



=== Lizenzierungs-Updates

Mit BlueXP  Disaster Recovery können Sie sich für eine kostenlose 90-Tage-Testversion anmelden, ein PAYGO-Abonnement (Pay-as-you-go) für Amazon Marketplace erwerben oder NetApp die BYOL-Lizenz (Bring-Your-Own-License) verwenden, die Sie von Ihrem NetApp Vertriebsmitarbeiter oder der NetApp Support-Website (NSS) erhalten.

Weitere Informationen zur Einrichtung einer Lizenzierung für die Disaster Recovery von BlueXP finden Sie unter link:../get-started/dr-licensing.html["Lizenzierung einrichten"].

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Erfahren Sie mehr über die Disaster Recovery von BlueXP"].



== 5 März 2024

Dies ist die Disaster Recovery-Version von BlueXP für die allgemeine Verfügbarkeit. Sie umfasst folgende Updates.



=== Lizenzierungs-Updates

Mit BlueXP  Disaster Recovery können Sie sich für eine kostenlose 90-Tage-Testversion anmelden oder Ihre eigene Lizenz (BYOL, Bring Your Own License) verwenden. Hierbei handelt es sich um eine NetApp Lizenzdatei (NLF), die Sie von Ihrem NetApp Vertriebsmitarbeiter erhalten. Sie können die Seriennummer der Lizenz verwenden, um das BYOL in der Digital Wallet von BlueXP zu aktivieren. Die Disaster-Recovery-Gebühren für BlueXP basieren auf der bereitgestellten Kapazität von Datastores.

Weitere Informationen zur Einrichtung einer Lizenzierung für die Disaster Recovery von BlueXP finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Lizenzierung einrichten"].

Weitere Informationen zum Verwalten von Lizenzen für *alle* BlueXP Services finden Sie unter https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Managen Sie Lizenzen für alle BlueXP Services"^].



=== Schichtpläne bearbeiten

Mit dieser Version können Sie jetzt Zeitpläne zum Testen von Compliance- und Failover-Tests einrichten, um sicherzustellen, dass diese bei Bedarf korrekt funktionieren.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie den Replizierungsplan"].



== Februar 2024

Diese BlueXP Disaster-Recovery-Vorschau enthält die folgenden Updates:



=== Netzwerkoptimierung

Mit diesem Release können Sie nun die Größe der VM-CPU- und RAM-Werte ändern. Sie können nun auch ein Netzwerk-DHCP oder eine statische IP-Adresse für die VM auswählen.

* DHCP: Wenn Sie diese Option wählen, geben Sie Anmeldeinformationen für die VM an.
* Statische IP: Sie können die gleichen oder andere Informationen aus der Quell-VM auswählen. Wenn Sie dieselbe Auswahl wie die Quelle wählen, müssen Sie keine Anmeldeinformationen eingeben. Wenn Sie jedoch andere Informationen aus der Quelle verwenden möchten, können Sie Anmeldeinformationen, IP-Adresse, Subnetzmaske, DNS und Gateway-Informationen angeben.


Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Benutzerdefinierte Skripts

Kann nun auch als Post Failover-Prozesse genutzt werden. Mit benutzerdefinierten Skripts kann die BlueXP Disaster Recovery Ihr Skript nach einem Failover-Prozess ausführen. Sie können beispielsweise ein benutzerdefiniertes Skript verwenden, um alle Datenbanktransaktionen nach Abschluss des Failovers wieder aufzunehmen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/failover.html["Failover an einen Remote-Standort"].



=== SnapMirror Beziehung

Sie können jetzt eine SnapMirror-Beziehung erstellen und gleichzeitig den Replizierungsplan entwickeln. Früher mussten Sie diese Beziehung außerhalb der Disaster Recovery von BlueXP aufbauen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Konsistenzgruppen

Bei der Erstellung eines Replizierungsplans können Sie VMs mit unterschiedlichen Volumes und unterschiedlichen SVMs einbeziehen. Die Disaster Recovery von BlueXP erstellt einen KonsistenzgruppenSnapshot, der alle Volumes enthält und alle sekundären Standorte aktualisiert.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== VM-Verzögerungsoption beim Einschalten

Wenn Sie einen Replikationsplan erstellen, können Sie VMs zu einer Ressourcengruppe hinzufügen. Mit Ressourcengruppen können Sie jede VM eine Verzögerung einstellen, sodass sie in einer verzögerten Reihenfolge hochgefahren werden.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Applikationskonsistente Snapshot Kopien

Sie können angeben, applikationskonsistente Snapshot Kopien zu erstellen. Der Service setzt die Applikation still und erstellt dann einen Snapshot, um einen konsistenten Status der Applikation zu erhalten.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



== 11 Januar 2024

Diese Vorschauversion des Disaster Recovery von BlueXP enthält die folgenden Updates:



=== Schnelleres Dashboard

Mit dieser Version können Sie schneller auf Informationen auf anderen Seiten über das Dashboard zugreifen.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Erfahren Sie mehr über BlueXP Disaster Recovery"].



== 20 Oktober 2023

Diese Vorschauversion des Disaster Recovery von BlueXP enthält die folgenden Updates.



=== Sichern Sie lokale NFS-basierte VMware Workloads

Mit der Disaster Recovery von BlueXP können Sie Ihre lokalen, NFS-basierten VMware-Workloads vor Ausfällen in eine andere lokale, NFS-basierte VMware Umgebung, zusätzlich zur Public Cloud, schützen. Mit BlueXP Disaster Recovery werden die Disaster-Recovery-Pläne orchestriert.


NOTE: Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Erfahren Sie mehr über die Disaster Recovery von BlueXP"].



== 27 September 2023

Diese Vorschauversion des Disaster Recovery von BlueXP enthält die folgenden Updates:



=== Dashboard-Updates

Sie können nun auf die Optionen im Dashboard klicken, um die Informationen schneller zu prüfen. Darüber hinaus wird im Dashboard jetzt der Status von Failover und Migrationen angezeigt.

Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/dashboard-view.html["Zeigen Sie den Zustand Ihrer Disaster-Recovery-Pläne auf dem Dashboard an"].



=== Aktualisierungen des Replikationsplans

* *RPO*: Sie können jetzt im Abschnitt Datastores des Replikationsplans den Wiederherstellungspunkt Objective (RPO) und Retention Count eingeben. Zeigt die Datenmenge an, die nicht älter als die eingestellte Zeit sein muss. Wenn Sie beispielsweise die Einstellung auf 5 Minuten festlegen, kann das System bei einem Zwischenfall bis zu 5 Minuten an Daten verlieren, ohne dass dies geschäftskritische Anforderungen beeinträchtigt.
+
Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].

* *Netzwerkverbesserungen*: Wenn Sie im Abschnitt „virtuelle Maschinen“ des Replikationsplans Netzwerke zwischen Quell- und Zielorten zuordnen, bietet BlueXP Disaster Recovery jetzt zwei Optionen: DHCP oder statische IP. Zuvor wurde nur DHCP unterstützt. Für statische IPs konfigurieren Sie die Subnetz-, Gateway- und DNS-Server. Darüber hinaus können Sie jetzt Anmeldeinformationen für virtuelle Maschinen eingeben.
+
Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].

* *Zeitpläne bearbeiten*: Sie können jetzt Replikationspläne aktualisieren.
+
Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/manage.html["Ressourcen managen"].

* *SnapMirror-Automatisierung*: Während Sie den Replizierungsplan in diesem Release erstellen, können Sie die SnapMirror Beziehung zwischen Quell- und Ziel-Volumes in einer der folgenden Konfigurationen definieren:
+
** 1 zu 1
** 1 zu vielen in einer Fanout-Architektur
** Von vielen zu 1 als Konsistenzgruppe
** Von vielen auf viele
+
Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].







== August 2023



=== BlueXP  Disaster Recovery-Vorschau

Die Disaster-Recovery-Vorschau von BlueXP ist ein Cloud-basierter Disaster-Recovery-Service, der Disaster-Recovery-Workflows automatisiert. Mit der BlueXP Disaster-Recovery-Vorschau können Sie zunächst Ihre lokalen NFS-basierten VMware-Workloads schützen, die NetApp Storage in VMware Cloud (VMC) auf AWS mit Amazon FSX for ONTAP ausführen.


NOTE: Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Erfahren Sie mehr über die Disaster Recovery von BlueXP"].

Diese Version enthält die folgenden Updates:



=== Ressourcengruppen werden für die Startreihenfolge aktualisiert

Wenn Sie einen Disaster Recovery- oder Replizierungsplan erstellen, können Sie virtuelle Maschinen zu funktionalen Ressourcengruppen hinzufügen. Mit Ressourcengruppen können Sie eine Reihe abhängiger virtueller Maschinen in logische Gruppen umwandeln, die Ihren Anforderungen entsprechen. Gruppen können beispielsweise die Startreihenfolge enthalten, die bei der Wiederherstellung ausgeführt werden kann. Mit diesem Release kann jede Ressourcengruppe eine oder mehrere virtuelle Maschinen enthalten. Die Virtual Machines werden basierend auf der Reihenfolge, in der Sie sie in den Plan aufnehmen, eingeschaltet. Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html#select-applications-to-replicate-and-assign-resource-groups["Wählen Sie Anwendungen aus, die Sie replizieren und Ressourcengruppen zuweisen möchten"].



=== Replizierungsüberprüfung

Nachdem Sie den Disaster Recovery- oder Replizierungsplan erstellt haben, identifizieren Sie die Wiederholung im Assistenten und initiieren Sie eine Replikation an einem Disaster Recovery-Standort. Alle 30 Minuten überprüft die BlueXP  Disaster Recovery, ob die Replikation tatsächlich gemäß dem Plan erfolgt. Sie können den Fortschritt auf der Seite Job Monitor überwachen. Siehe  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/replicate.html["Replizierung von Applikationen an einen anderen Standort"].



=== Der Replizierungsplan zeigt die Zeitpläne für die Übertragung der Recovery Point Objective (RPO) an

Wenn Sie einen Disaster Recovery- oder Replizierungsplan erstellen, wählen Sie die VMs aus. In diesem Release können Sie jetzt die SnapMirror anzeigen, die mit jedem der Volumes verknüpft sind, die dem Datenspeicher oder der VM zugeordnet sind. Sie können auch die mit dem SnapMirror Zeitplan verknüpften RPO-Übertragungszeitpläne anzeigen. Anhand des RPO können Sie feststellen, ob Ihr Backup-Zeitplan für die Wiederherstellung nach einem Ausfall ausreicht. Siehe https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Erstellen Sie einen Replizierungsplan"].



=== Jobüberwachung aktualisieren

Die Seite Job Monitor enthält jetzt eine Option Aktualisieren, damit Sie den aktuellen Status der Vorgänge abrufen können. Siehe  https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/monitor-jobs.html["Überwachen Sie Disaster-Recovery-Jobs"].



== 18 Mai 2023

Dies ist die erste Version der Disaster Recovery von BlueXP.



=== Cloud-basierter Disaster Recovery-Service

BlueXP Disaster Recovery ist ein Cloud-basierter Disaster Recovery Service, der Disaster Recovery Workflows automatisiert. Mit der BlueXP Disaster-Recovery-Vorschau können Sie zunächst Ihre lokalen NFS-basierten VMware-Workloads schützen, die NetApp Storage in VMware Cloud (VMC) auf AWS mit Amazon FSX for ONTAP ausführen.

link:https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-intro.html["Erfahren Sie mehr über die Disaster Recovery von BlueXP"].
